<?php

/* 
**  ===========
**  PlaatEnergy
**  ===========
**
**  Created by wplaat
**
**  For more information visit the following website.
**  Website : www.plaatsoft.nl 
**
**  Or send an email to the following address.
**  Email   : info@plaatsoft.nl
**
**  All copyrights reserved (c) 2008-2016 PlaatSoft
*/

// Database credentials
$dbhost = "127.0.0.1";
$dbname = "test2";
$dbuser = "test2";
$dbpass = "test2";

/* Enable MySQL (else PostgreSQL) */
define('MYSQL', 1);

/* Enable debug mode -> If enabled SQL is logged */
define('DEBUG', 0);

?>
