<?php

/* 
**  ===========
**  PlaatEnergy
**  ===========
**
**  Created by wplaat
**
**  For more information visit the following website.
**  Website : www.plaatsoft.nl 
**
**  Or send an email to the following address.
**  Email   : info@plaatsoft.nl
**
**  All copyrights reserved (c) 2008-2016 PlaatSoft
*/

$dbhost = "127.0.0.1";
$dbuser = "plaatenergy";
$dbpass = "plaatenergy";
$dbname = "plaatenergy";

?>
