<?php

/* 
**  ===========
**  PlaatEnergy
**  ===========
**
**  Created by wplaat
**
**  For more information visit the following website.
**  Website : www.plaatsoft.nl 
**
**  Or send an email to the following address.
**  Email   : info@plaatsoft.nl
**
**  All copyrights reserved (c) 2008-2016 PlaatSoft
*/

define('PAGE_HOME',          1000);
define('PAGE_ABOUT',         1001);
define('PAGE_DONATE',        1002);
define('PAGE_RELEASE_NOTES', 1003);
define('PAGE_REPORT',        1004);

define('PAGE_YEARS_IN_KWH',  1005);
define('PAGE_YEAR_IN_KWH',   1006);
define('PAGE_MONTH_IN_KWH',  1007);
define('PAGE_DAY_IN_KWH',    1008);

define('PAGE_YEARS_IN_M3',   1009);
define('PAGE_YEAR_IN_M3',    1010);
define('PAGE_MONTH_IN_M3',   1011);
define('PAGE_DAY_IN_M3',     1012);

define('PAGE_YEARS_OUT_KWH', 1013);
define('PAGE_YEAR_OUT_KWH',  1014);
define('PAGE_MONTH_OUT_KWH', 1015);
define('PAGE_DAY_OUT_KWH',   1016);

define('EVENT_PREV',         2000);
define('EVENT_NEXT',         2001);

?>
